export const cards = {
  types: ["bug", "tree", "cloud", "shell"] as const, // circular type-advantages (i.e. bug -> tree -> cloud -> shell -> bug)

  rarities: ["kilo", "mega", "giga", "tera", "peta", "exa"] as const,

  typeAdvantageEffects: {
    notEffective: 0.9,
    normal: 1,
    superEffective: 1.15,
  },

  default: [
    {
      name: "foo",
      type: "bug",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 500,
      defence: 300,
    },
    {
      name: "bar",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 300,
      defence: 500,
    },
    {
      name: "baz",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 400,
      defence: 400,
    },
    {
      name: "quux",
      type: "shell",
      rarity: "kilo",
      drop_rate: 9700,
      attack: 500,
      defence: 350,
    },
    {
      name: "corge",
      type: "bug",
      rarity: "kilo",
      drop_rate: 9500,
      attack: 600,
      defence: 400,
    },
    {
      name: "grault",
      type: "tree",
      rarity: "kilo",
      drop_rate: 9400,
      attack: 500,
      defence: 500,
    },
    {
      name: "garply",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 9300,
      attack: 800,
      defence: 250,
    },
    {
      name: "waldo",
      type: "shell",
      rarity: "kilo",
      drop_rate: 9200,
      attack: 550,
      defence: 450,
    },

    {
      name: "fred",
      type: "bug",
      rarity: "mega",
      drop_rate: 8700,
      attack: 1000,
      defence: 1000,
    },
    {
      name: "plugh",
      type: "tree",
      rarity: "mega",
      drop_rate: 8500,
      attack: 1800,
      defence: 800,
    },
    {
      name: "xyzzy",
      type: "cloud",
      rarity: "mega",
      drop_rate: 8300,
      attack: 2500,
      defence: 400,
    },
    {
      name: "thud",
      type: "shell",
      rarity: "mega",
      drop_rate: 8100,
      attack: 2500,
      defence: 1500,
    },
    {
      name: "blarg",
      type: "bug",
      rarity: "mega",
      drop_rate: 8000,
      attack: 2800,
      defence: 1200,
    },
    {
      name: "boogle",
      type: "tree",
      rarity: "mega",
      drop_rate: 7800,
      attack: 2000,
      defence: 2500,
    },
    {
      name: "bazola",
      type: "cloud",
      rarity: "mega",
      drop_rate: 7500,
      attack: 2000,
      defence: 3000,
    },

    {
      name: "mum",
      type: "shell",
      rarity: "giga",
      drop_rate: 6500,
      attack: 2500,
      defence: 3500,
    },
    {
      name: "puppu",
      type: "shell",
      rarity: "giga",
      drop_rate: 6500,
      attack: 4000,
      defence: 2000,
    },
    {
      name: "alice",
      type: "tree",
      rarity: "giga",
      drop_rate: 6000,
      attack: 2800,
      defence: 2200,
    },
    {
      name: "jim",
      type: "tree",
      rarity: "giga",
      drop_rate: 6000,
      attack: 3200,
      defence: 4000,
    },
    {
      name: "sheila",
      type: "cloud",
      rarity: "giga",
      drop_rate: 5700,
      attack: 3000,
      defence: 5500,
    },
    {
      name: "shme",
      type: "bug",
      rarity: "giga",
      drop_rate: 5500,
      attack: 500,
      defence: 7000,
    },

    {
      name: "fish",
      type: "bug",
      rarity: "tera",
      drop_rate: 4400,
      attack: 4200,
      defence: 5800,
    },
    {
      name: "wombat",
      type: "bug",
      rarity: "tera",
      drop_rate: 4400,
      attack: 5000,
      defence: 4500,
    },
    {
      name: "pluto",
      type: "tree",
      rarity: "tera",
      drop_rate: 3800,
      attack: 6500,
      defence: 3200,
    },
    {
      name: "toto",
      type: "cloud",
      rarity: "tera",
      drop_rate: 3500,
      attack: 6000,
      defence: 4000,
    },

    {
      name: "gorp",
      type: "cloud",
      rarity: "peta",
      drop_rate: 1500,
      attack: 7000,
      defence: 400,
    },
    {
      name: "noot",
      type: "tree",
      rarity: "peta",
      drop_rate: 1200,
      attack: 1000,
      defence: 9000,
    },
    {
      name: "paperino",
      type: "bug",
      rarity: "peta",
      drop_rate: 1000,
      attack: 8000,
      defence: 2000,
    },

    {
      name: "ztesch",
      type: "cloud",
      rarity: "exa",
      drop_rate: 100,
      attack: 9500,
      defence: 9500,
    },
    {
      name: "zork",
      type: "shell",
      rarity: "exa",
      drop_rate: 1,
      attack: 10000,
      defence: 10000,
    },
  ] as const,
};
