export const cards = {
  types: ["bug", "tree", "cloud", "shell"] as const, // circular type-advantages (i.e. bug -> tree -> cloud -> shell -> bug)

  rarities: ["kilo", "mega", "giga", "tera", "peta", "exa"] as const,

  typeAdvantageEffects: {
    notEffective: 0.9,
    normal: 1,
    superEffective: 1.15,
  },

  default: [
    {
      name: "foo",
      type: "bug",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 5000,
      defense: 5000,
    },
    {
      name: "bar",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 9500,
      attack: 6000,
      defense: 1000,
    },
    {
      name: "baz",
      type: "shell",
      rarity: "kilo",
      drop_rate: 9000,
      attack: 6000,
      defense: 500,
    },
    {
      name: "quux",
      type: "tree",
      rarity: "kilo",
      drop_rate: 5000,
      attack: 100,
      defense: 10000,
    },
    {
      name: "corge",
      type: "tree",
      rarity: "kilo",
      drop_rate: 1000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "grault",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "garply",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "waldo",
      type: "shell",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "fred",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "plugh",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "xyzzy",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "thud",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "blarg",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "mum",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "puppu",
      type: "shell",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "alice",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "bazola",
      type: "bug",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "boogle",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "fish",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "gorp",
      type: "bug",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "jim",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "noot",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "paperino",
      type: "shell",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "pluto",
      type: "bug",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "sheila",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "wombat",
      type: "shell",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "toto",
      type: "tree",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "ztesch",
      type: "cloud",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
    {
      name: "zork",
      type: "shell",
      rarity: "kilo",
      drop_rate: 10000,
      attack: 10000,
      defense: 10000,
    },
  ] as const,
};
